### ISSUE TITLE
Menu interaction

### ISSUE THREAD

**Issue by SoulReaper4720** [CryptoGenics/esx_CryptoCustoms#4]
Hi, I’m having an issue with the menus. So I see the blips for them, but when I enter the blip I do not get the option to press any button while standing inside of the blip, until I restart the resource. Is there something missing on my end that doesn’t loop the resource restart for the menus? And if so, where do I add it?

Thank you for your time.

**Comment by rahafuf** [comment]
im having the same issue. surprised this hasnt been resolved yet

**Comment by CryptoGenics** [comment]
There is no known issue in this repo. Sounds like you need to have your job set at cardealer?

**Comment by rahafuf** [comment]
i actually got it resolved. my issue was that the first vehicle category was blank. once i removed the blank one it was resolved.
