### ISSUE TITLE
Resell Vehicles

### ISSUE THREAD

**Issue by rahafuf** [CryptoGenics/esx_CryptoCustoms#5]
when the resource is set to not player managed you have no option to resell vehicles which in turn limits how many vehicles you can have. in the coding I can see the option is still listed from esx_vehicleshop but it is not functional. How can we resolve this?

**Comment by CryptoGenics** [comment]
this is made to use along side of esx_vehicleshop so have the esx_vehicleshop not player managed

**Comment by rahafuf** [comment]
even with it not player managed you couldnt sell vehicles there. i got it fixed by updating the esx_CryptoCustoms coding
